name: manzanita victorian
favicon: null
layout_spectrum: 0.17463807994499803
typography_spectrum: 0.7241118215024471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6762426891364157
  lightness: 0.7886221040971577
  saturation: 0.004558919696137309
  rhythmicContrast: 0
purpose: []
